[package]
name = "resolv"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
axum = { version = "0.8.9", features = ["macros"] }
dotenvy = "0.15.7"
serde = { version = "1.0", features = ["derive"] }
# sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "time",
    "uuid",
] }
time = {version = "0.3.47", features = ["serde", "macros"]}
tokio = { version = "1", features = ["full"] }
# \Transport Layer Security (TLS)
